### PR TITLE
Fix Bulgaria alpha3 country code

### PR DESCRIPTION
**Pull request by badreddine-dlaila**
https://www.iso.org/obp/ui/#iso:code:3166:BG

### CODE REVIEW

**Comment by alexinea** [comment]
The content of iso3166 is very detailed, thank you very much.

**Comment by badreddine-dlaila** [comment]
Quick question @alexinea, Nuget packages are built/released after each merge or it's a manual process ?

**Comment by alexinea** [comment]
It is now handled manually. 😂

**Comment by badreddine-dlaila** [comment]
> It is now handled manually. 😂

Can we do something about that ? how can I help ?
Actually, I need updated version to fix typo issues for China and Bulgaria 😢

**Comment by alexinea** [comment]
I have submitted the package to nuget :)

"Automatic release" In my plan, I will follow the plan step by step 😁

**Pull request merged**
